# _config.yml - Final Configuration for a Documentation Site

# --- Basic Site Settings ---
title: "LFCS Notes"
description: "A personal study guide for the LFCS certification."
url: "https://dozamo.github.io"
baseurl: "/lfcs"

# --- Theme and Skin ---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-github-metadata

# --- Collections (This part is correct and we keep it) ---
collections:
  lab_setup:
    output: true
    permalink: /lab/:path/
  essential_commands:
    output: true
    permalink: /essential-commands/:path/
  users_groups:
    output: true
    permalink: /users-groups/:path/
  networking:
    output: true
    permalink: /networking/:path/
  storage:
    output: true
    permalink: /storage/:path/
  operations_deployment:
    output: true
    permalink: /operations-deployment/:path/
  bonus:
    output: true
    permalink: /bonus/:path/

# --- Defaults ---
# This tells every page to use the "single" layout and look for our new sidebar
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      sidebar:
        nav: "docs_sidebar" # We will create this new sidebar definition