# =============================================================================
# _config.yml - Final Configuration for LFCS Notes
# Theme: Minimal Mistakes
# Workflow: GitHub Actions
# =============================================================================

# --- Basic Site Settings ---
title: "LFCS Notes"
description: "A personal study guide for the LFCS certification."
url: "https://dozamo.github.io"  # The base hostname & protocol for your site
baseurl: "/lfcs"                 # The subpath of your site, e.g. /blog

# --- Theme and Skin ---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # Use "default" for light mode

# --- Plugins ---
# These are managed by the Gemfile and used by the GitHub Actions workflow.
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-github-metadata

# --- Collections ---
# This is the core of the agile workflow. Each section of your study guide
# is a collection, corresponding to a folder with a leading underscore.
# To add a note, you simply add a Markdown file to the appropriate folder.
collections:
  lab_setup:
    output: true
    permalink: /lab/:path/
  essential_commands:
    output: true
    permalink: /essential-commands/:path/
  users_groups:
    output: true
    permalink: /users-groups/:path/
  networking:
    output: true
    permalink: /networking/:path/
  storage:
    output: true
    permalink: /storage/:path/
  operations_deployment:
    output: true
    permalink: /operations-deployment/:path/
  bonus:
    output: true
    permalink: /bonus/:path/

# --- Defaults ---
# Global front matter settings to apply to all files, keeping them clean.
defaults:
  - scope:
      path: "" # Apply to all files in the project
    values:
      layout: "single"      # The standard layout for content pages
      sidebar:
        nav: "main_sidebar" # All pages will use the sidebar defined in _data/navigation.yml
      show_pagination: true # Enable Previous/Next links for documents within a collection
