# _config.yml - Configuración para Minimal Mistakes

title: "LFCS Notes"
description: "Notes and guides for LFCS certification."
url: "https://dozamo.github.io" # La URL base de tu sitio
baseurl: "/lfcs" # El subdirectorio de tu proyecto

# --- Selección del Tema ---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # Opciones: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "sunrise", "default"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache

# --- Navegación Principal (Sidebar) ---
# Usaremos un archivo de datos para controlar esto

# --- Defaults para todas las páginas ---
defaults:
  - scope:
      path: "" # Aplicar a todos los archivos
      type: "pages" # Solo a páginas, no a posts
    values:
      layout: "single" # El layout por defecto para una página de contenido
      sidebar:
        nav: "main" # Le dice que use la navegación definida en 'main' en el archivo de datos
      show_pagination: true
      show_title: false  # <-- ¡AQUÍ ESTÁ LA LÍNEA MÁGICA GLOBAL!

# --- Configuración de la Lectura ---
# Muestra los enlaces de paginación Anterior/Siguiente
# en la parte inferior de las páginas de contenido.
paginator:
  enabled: true
