# El "cerebro" de tu sitio de documentación
title: My LFCS Study Guide 
description: Notes and guides for LFCS certification.

# --- La línea mágica ---
# Esto le dice a GitHub Pages que use el tema "Just the Docs"
remote_theme: just-the-docs/just-the-docs

# Opcional: añade un esquema de color. Prueba 'dark' o déjalo comentado.
color_scheme: dark

