title: LFCS Notes
description: Notes and guides for LFCS certification.

remote_theme: just-the-docs/just-the-docs@v0.7.0

color_scheme: dark

# --- La única configuración de prueba ---
page_navigation: true
