# _config.yml

# --- Basic Site Settings ---
title: "LFCS Notes"
description: "A personal study guide for the LFCS certification."
url: "https://dozamo.github.io"
baseurl: "/lfcs"

# --- Theme and Skin ---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-github-metadata

# --- Collections ---
# Defines our content sections. Each one corresponds to a folder.
collections:
  lab_setup:
    output: true
    permalink: /lab/:path/
  essential_commands:
    output: true
    permalink: /essential-commands/:path/
  users_groups:
    output: true
    permalink: /users-groups/:path/
  networking:
    output: true
    permalink: /networking/:path/
  storage:
    output: true
    permalink: /storage/:path/
  operations_deployment:
    output: true
    permalink: /operations-deployment/:path/
  bonus:
    output: true
    permalink: /bonus/:path/

# --- Defaults ---
# Global settings for all pages to keep things DRY (Don't Repeat Yourself)
defaults:
  - scope:
      path: "" # Apply to all files
    values:
      layout: "single" # Use the standard content layout
      sidebar:
        nav: "main" # All pages will use the main sidebar
      show_pagination: true # Enable Previous/Next links for collection items