# El "cerebro" de tu sitio de documentación
title: LFCS Notes
description: Notes and guides for LFCS certification.

# --- La línea mágica ---
# Esto le dice a GitHub Pages que use el tema "Just the Docs"
remote_theme: just-the-docs/just-the-docs@v0.10.1

# Opcional: añade un esquema de color. Prueba 'dark' o déjalo comentado.
color_scheme: dark

# Forcing a rebuild
# Para abrir enlaces externos en una nueva pestaña
links:
    external: true
    external_links: true
