# ./mkdocs.yml
site_name: LFCS Notes
site_url: https://dozamo.github.io/lfcs
repo_url: https://github.com/dozamo/lfcs
repo_name: dozamo/lfcs

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
#    - header.autohide: false
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: amber
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Welcome: index.md
  - Lab Environment Setup:
      - Overview: lab-setup/index.md
      - Provision CentOS VM: lab-setup/01-provision-centos-kvm.md
      - Provision Ubuntu VM: lab-setup/02-provision-ubuntu-kvm.md
  - Useful Resources: resources.md


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - abbr
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dozamo
        #    - icon: fontawesome/brands/linkedin
        #      link: https://linkedin.com/in/TU-PERFIL

        #extra_css:
        #  - stylesheets/extra.css

